### ISSUE TITLE
time travel doesn't work with redux devtools

### ISSUE THREAD

**Issue by phra** [ngrx/store-devtools#33] opened 2016-10-28 09:43 UTC
hi,

i'm trying to use the official redux devtools extensions for chrome but i can't use the slider to time travel between states and in the inspector tab i can't revert/skip/dispatch actions. 

did someone have experienced the same problem?

**Comment by phra** [comment] 2016-10-28 10:20
`postMessage` is undefined, that's the error. does someone know how to fix it?

![screenshot from 2016-10-28 12-18-00](https://cloud.githubusercontent.com/assets/984628/19803392/b94c20ba-9d08-11e6-81a1-be8aef45e0df.png)

**Comment by maxime1992** [comment] 2016-10-28 12:26
See https://github.com/ngrx/store-devtools/issues/34#issuecomment-256907397 and give a try with Firefox.

**Comment by phra** [comment] 2016-10-28 12:29
@maxime1992 i'm not using immutablejs atm nor the freeze reducer and it's not working on chromium 53.

**Comment by woutervandergraaf** [comment] 2016-10-28 13:38
See [zalmoxisus/redux-devtools-extension#238](https://github.com/zalmoxisus/redux-devtools-extension/issues/238#issuecomment-256230820). Wait till ngrx/store-devtools 3.3.0 becomes available or revert to extension 2.8.3.

**Comment by phra** [comment] 2016-10-28 13:44
@woutervandergraaf thank you.

**Comment by phra** [comment] 2016-10-28 13:45
i'll leave it open until 3.3.0 is released so people can see it.

**Comment by rob3c** [comment] 2016-10-28 19:16
While there are other issues preventing this from working, it looks like one potential issue is in the `connect()` function in `extension.ts`:. Instead of returning a lambda `return () => connection.unsubscribe();` from the wrapping Observable for later invocation when the subscriber cancels the subscription, it calls `return connection.subscribe();` directly, thus immediately canceling the subscription for the update stream from the extension.

**Comment by zalmoxisus** [comment] 2016-10-29 09:45
The regression should be fixed in `2.8.5` of the extension.

**Comment by maxime1992** [comment] 2016-11-04 07:23
@zalmoxisus hi, sorry it took me so long to try it, but the extension is still has a weird behaviour on chrome. The extension version I'm using is 2.9.0.2.

Everything works just fine on Firefox.

Am I missing something ?

If there's anything I can do to help let me know (detailed logs, I can also give you the git project I'm working on as it's open source so maybe you can compare what's wrong between FF and Chrome, etc).

**Comment by zalmoxisus** [comment] 2016-11-04 08:15
@maxime1992, yes, please write the exact steps to reproduce the problem with your example. I have been using [`example-app`](https://github.com/ngrx/example-app) and it seems to works as expected.

**Comment by maxime1992** [comment] 2016-11-04 08:27
[example-app](https://github.com/ngrx/example-app) probably works because it's not using ImmutableJs, is it ?

To reproduce : 
```
git clone https://gitlab.com/victornoel/petals-cockpit.git
cd petals-cockpit/frontend
npm i
./node_modules/angular-cli/bin/ng serve
```

Open Chrome and Firefox at [http://localhost:4200/cockpit/workspaces](http://localhost:4200/cockpit/workspaces).

Open Redux extension on both and try to undo the `USR_IS_CONNECTED` action.
If it works (on Firefox you should see it), the "administrator" text (top left) should be removed.

**Comment by phra** [comment] 2016-11-04 09:18
@maxime1992 yeah, the example-app is using the official reducer (meant to be used only in dev env) in order to have immutable structures. look at https://github.com/ngrx/example-app/blob/f15733dd3f3f0346405fdfbd214ea73c6fef00dc/src/app/reducers/index.ts#L26

**Comment by maxime1992** [comment] 2016-11-04 09:27
@phra Oh I see. Thanks for pointing that out.

(But still, there's a problem as FF and Chrome app does not handle the same web-app the same way.)

**Closed** 2016-11-04 12:31 UTC

**Comment by zalmoxisus** [comment] 2016-11-04 12:32
@maxime1992  thanks for the example. It turns out that 6 days ago when I was testing,  it was fixed, but lately some changes "spoiled" it. 

The problem is that `store-devtools` subscribes to the extension then [unsubscribes imediately](https://github.com/ngrx/store-devtools/pull/37/commits/f46a2a19116e3169737d236281ce74a84d5bedcd).

In the earlier versions (which is on Firefox), [unsubscribing just didn't work](https://github.com/zalmoxisus/redux-devtools-extension/commit/d81a7de0b28db5aca8fe6695f84f6d420ff6d437).

It's fixed now in #37,

**Comment by MikeRyan52** [comment] 2016-11-04 12:34
Released as version 3.2.2

**Comment by maxime1992** [comment] 2016-11-04 12:44
@zalmoxisus & @MikeRyan52 I upgraded to 3.2.2 and it's working great, awesome :)
Thanks

**Comment by phra** [comment] 2016-11-04 13:15
YEAH!

**Comment by phra** [comment] 2016-11-21 22:42
for me is not working anymore. (tested w/ latest redux devtools, ngrx/example-app and chromium 53).
is it working for you guys?

**Comment by zalmoxisus** [comment] 2016-11-22 10:10
@phra could you please check [example-app](https://github.com/ngrx/example-app) with updated `@ngrx/store-devtools@3.2.2`? I just tried it and don't see any problems.

**Comment by phra** [comment] 2016-11-22 14:55
@zalmoxisus yeah, i tried yesterday evening and it was not working. :crying_cat_face:
i tried again now and yes, time traveling and skipping actions are not working on my laptop. (i've updated manually `store-devtools` to `3.2.2`)

![screenshot from 2016-11-22 15-56-35](https://cloud.githubusercontent.com/assets/984628/20528316/07d8984a-b0cc-11e6-9993-6dad558a039b.png)

**Comment by zalmoxisus** [comment] 2016-11-22 15:55
@phra, is the extension's version `2.10.3`?

**Comment by phra** [comment] 2016-11-22 16:08
@zalmoxisus yeah, that's the problem! the autoupdate of chromium wasn't working and by reinstalling manually the extensions fixed all the problems. thank you!

**Comment by zalmoxisus** [comment] 2016-11-22 16:15
You're welcome. It's a news for me that Chromium doesn't autoupdate the extensions as Chrome does. We need to handle that on the extension side then (showing a notification `A new version is available`).

**Comment by phra** [comment] 2016-11-22 16:41
i think that there is an autoupdate feature but it wasn't automatically updating that extension, also if i was forcing the update via the button in the extensions panel. i'm on kali linux and i'm running chromium v53 and i don't know if it is the latest stable available worldwide, but is the latest one available on kali linux repository.
